version:
  host: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/rentacar
    username: postgres
    password: eras
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true