spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/rentacar
    username: postgres
    password: eras
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true